# Generated by Django 6.0.2 on 2026-02-28 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_review_applied_for_refund_refundapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefundApplication',
        ),
    ]
