# Generated by Django 6.0.2 on 2026-02-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_size_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='product',
            field=models.ManyToManyField(related_name='sizes', to='product.product'),
        ),
    ]
