# Generated by Django 6.0.2 on 2026-02-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_size_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='sizes', to='product.product'),
        ),
    ]
