# Generated by Django 6.0.2 on 2026-02-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_size_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='product',
        ),
    ]
