# Generated by Django 6.0.2 on 2026-02-26 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
