# Generated by Django 6.0.2 on 2026-02-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_unique_together_and_more'),
        ('product', '0009_remove_product_sizes_remove_product_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
