# Generated by Django 6.0.2 on 2026-02-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_variant_color_variantcolour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='stock',
        ),
        migrations.AddField(
            model_name='variantcolour',
            name='stock',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
