# Generated by Django 6.0.2 on 2026-02-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_variant_stock_variantcolour_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visits',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
