# Generated by Django 6.0.2 on 2026-02-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0009_remove_product_sizes_remove_product_stock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
