# Generated by Django 6.0.2 on 2026-02-28 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user_email',
        ),
    ]
