# Generated by Django 6.0.2 on 2026-02-28 04:28

import django.db.models.deletion
import product.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_payment_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='amount',
        ),
        migrations.AddField(
            model_name='refund',
            name='attachment',
            field=models.FileField(default=1, upload_to='refunds/', validators=[product.validators.validate_file_size]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='refund',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='order.order'),
        ),
    ]
